### ISSUE TITLE
WASD is not usable

### ISSUE THREAD

**Issue by pietrodn** [eleKit/the-last-drop#10]
It's very hard to play using the WASD keys (e.g. on WebGL) because for example when the drop is falling down and I press D, the drop stops falling and goes only to the right.
Also, the drop is allowed to go up, and that shouldn't be the case.

I propose to implement an "additive" WASD, like this:

    // Fix for WASD keys
    
    Vector3 grav = Vector3.zero;
    
    if (Input.GetKeyDown (KeyCode.W)) {
    	grav += new Vector3 (0f, gravityValue, 0f);
    }
    if (Input.GetKeyDown (KeyCode.A)) {
    	grav += new Vector3 (-gravityValue, 0f, 0f);
    }
    if (Input.GetKeyDown (KeyCode.S)) {
    	grav += new Vector3 (0f, -gravityValue, 0f);
    }
    if (Input.GetKeyDown (KeyCode.D)) {
    	grav += new Vector3 (gravityValue, 0f, 0f);
    }
    
    Physics2D.gravity = grav;

In this way multiple keys may be pressed at a time and the motion would be better.

**Comment by eleKit** [comment]
Thank you for the advice... but this is a game for phones :)
It uses gyroscope and gravity goes down!!
